#!/usr/bin/env bash
# Pre-provision every OCR asset the runtime needs, with checksum verification.
#
# Runs at IMAGE BUILD time (network available, supervised). Never at runtime.
# After this has run, runtime parsing must not download anything — that is the
# property STAGE2_RUNTIME_REQUIREMENTS §6 measurement 9 exists to prove.
#
#   ./fetch-ocr-assets.sh <dest>              verify mode  (default; fails closed)
#   ./fetch-ocr-assets.sh --record <dest>     record mode  (prints real sha256s)
#
# Verify mode refuses to install anything whose hash is __RECORD__ or whose
# bytes do not match the lock. Record mode is the only way to obtain hashes and
# is deliberately a separate, explicit action.
set -euo pipefail
cd "$(dirname "$0")"

RECORD=0
if [ "${1:-}" = "--record" ]; then RECORD=1; shift; fi
DEST="${1:-/opt/ocr-assets}"
LOCK="./ocr-assets.lock"

[ -f "$LOCK" ] || { echo "!! $LOCK missing" >&2; exit 1; }
mkdir -p "$DEST"

sha() { command -v sha256sum >/dev/null && sha256sum "$1" | cut -d' ' -f1 || shasum -a 256 "$1" | cut -d' ' -f1; }

total=0; ok=0; recorded=0
declare -a RECORDED_LINES=()

while read -r rel want url; do
  case "$rel" in ''|'#'*) continue ;; esac
  total=$((total+1))
  out="$DEST/$rel"
  mkdir -p "$(dirname "$out")"

  if [ ! -f "$out" ]; then
    echo "==> fetching $rel"
    if ! curl -fsSL --retry 3 --max-time 600 -o "$out" "$url"; then
      echo "!! download failed: $url" >&2
      rm -f "$out"
      exit 1
    fi
  fi

  got="$(sha "$out")"

  if [ "$want" = "__RECORD__" ]; then
    if [ "$RECORD" -eq 1 ]; then
      echo "    recorded $rel  $got"
      RECORDED_LINES+=("$rel  $got  $url")
      recorded=$((recorded+1))
      continue
    fi
    echo "!! $rel has no recorded checksum (__RECORD__) and --record was not given." >&2
    echo "   Refusing to install an unverified OCR asset into the image." >&2
    echo "   Run: ./fetch-ocr-assets.sh --record $DEST" >&2
    exit 1
  fi

  if [ "$got" != "$want" ]; then
    echo "!! CHECKSUM MISMATCH for $rel" >&2
    echo "   expected $want" >&2
    echo "   actual   $got" >&2
    echo "   The upstream artifact changed under a pinned URL. Do not proceed." >&2
    exit 1
  fi
  ok=$((ok+1))
done < "$LOCK"

if [ "$RECORD" -eq 1 ]; then
  echo
  echo "===== paste these into ocr-assets.lock, then re-run WITHOUT --record ====="
  printf '%s\n' "${RECORDED_LINES[@]}"
  echo "========================================================================="
  echo "recorded=$recorded verified=$ok total=$total"
  # Record mode is provisioning, not acceptance. Never let a build treat it as
  # success.
  exit 3
fi

echo "==> OCR assets verified: $ok/$total"
[ "$ok" -eq "$total" ] || { echo "!! not all assets verified" >&2; exit 1; }

# Manifest the runtime reads to decide readiness. If this file is absent or
# incomplete, the gateway must report not-ready rather than parse a CV and
# quietly reach the network.
{
  echo "# generated by fetch-ocr-assets.sh — do not edit"
  echo "asset_count=$ok"
  while read -r rel want url; do
    case "$rel" in ''|'#'*) continue ;; esac
    echo "asset=$rel"
  done < "$LOCK"
} > "$DEST/MANIFEST"

echo "==> wrote $DEST/MANIFEST"
