// Résumé parsing — capability wiring, no model.
//
// The whole feature, expressed as: read the document, parse it, extract fields,
// raise a PROPOSAL. Nothing here writes to a candidate; `ProposalService` and
// the aggregate own that, and a human still has to accept every field.
//
// WORKS WITH NO AI CONFIGURED. If either capability is absent the task ABSTAINS
// with a reason. Abstention is a normal outcome, not an error — the candidate
// record is unaffected and the recruiter carries on typing.

import type {
  AICapabilities, AIOutcome, ExtractedResume, ParsedDocument,
} from '../../modules/shared/kernel/ai/index.js';
import { isProposal } from '../../modules/shared/kernel/ai/index.js';
import type { DocumentStore } from '../../modules/talent/index.js';

/**
 * One parse, two possible destinations.
 *
 * A CV attached to an existing candidate produces a PROPOSAL; a file staged in
 * an intake batch has no candidate to propose against, so the result is
 * recorded on the intake item instead. The parsing itself is identical, which
 * is why this is a union of targets rather than a second pipeline.
 */
export interface ParseInput {
  readonly candidateId?: number;
  readonly batchId?: number;
  readonly itemId?: string;
  readonly documentId: string;
  readonly fileHash: string;
  readonly fileName: string;
  readonly mimeType: string;
}

export interface ProposedFieldInput {
  readonly field: string;
  readonly value: unknown;
  readonly confidence: number;
  readonly evidence: string | null;
}

/**
 * Everything needed to reproduce this proposal exactly.
 *
 * Model alone is not enough: the same model behind a different parser or a
 * different prompt version produces different output. When a model is upgraded
 * this is what tells you which proposals were generated by the old one.
 */
export interface GenerationProvenance {
  readonly capability: string;
  readonly modelId: string;
  /** Digest of the exact weights, when the runtime reports one. See AIProvenance. */
  readonly modelDigest?: string | null;
  readonly promptVersionId: string;
  readonly documentHash: string | null;
  readonly parserVersion: string | null;
  readonly extractorVersion: string | null;
  readonly generatedAt: Date;
}

export type HandlerOutcome =
  | {
      readonly kind: 'PROPOSAL';
      readonly fields: readonly ProposedFieldInput[];
      readonly generation: GenerationProvenance;
    }
  | { readonly kind: 'ABSTAIN'; readonly reason: string; readonly permanent: boolean };

/**
 * Map an extraction onto candidate fields.
 *
 * MAPPING ONLY — no inference and no defaulting. A field the extractor did not
 * produce is simply absent from the proposal rather than proposed as null,
 * because "I did not find a phone number" and "this person has no phone number"
 * are different claims and only one of them is safe to write.
 *
 * `uncertainFields` halves the per-field confidence so the review screen can
 * highlight exactly what the extractor was unsure about. One confidence number
 * for a whole résumé hides that the name was certain and the phone was a guess.
 */
export const toProposedFields = (
  resume: ExtractedResume,
  baseConfidence: number,
): readonly ProposedFieldInput[] => {
  const uncertain = new Set(resume.uncertainFields);
  const fields: ProposedFieldInput[] = [];

  const add = (field: string, value: unknown, evidence: string | null = null): void => {
    if (value === undefined || value === null) return;
    if (typeof value === 'string' && value.trim() === '') return;
    if (Array.isArray(value) && value.length === 0) return;
    fields.push({
      field,
      value,
      confidence: uncertain.has(field) ? baseConfidence / 2 : baseConfidence,
      evidence,
    });
  };

  add('fullName', resume.fullName);
  add('email', resume.email);
  add('phone', resume.phone);
  add('location', resume.location);
  add('yearsExperience', resume.totalYearsExperience);
  add('skills', resume.skills);
  add('languages', resume.languages);
  add('certifications', resume.certifications);

  // Current role: the employment entry marked current, else the most recent.
  const current = resume.employment.find((e) => e.current === true) ?? resume.employment[0];
  if (current !== undefined) {
    add('currentCompany', current.employer, `employment: ${current.employer}`);
    add('currentPosition', current.title, `employment: ${current.employer}`);
  }

  const education = resume.education[0];
  if (education !== undefined) {
    add('university', education.institution, 'education');
    add('major', education.field, 'education');
    const year = Number(education.to);
    if (Number.isInteger(year) && year >= 1900 && year <= 2200) {
      add('graduationYear', year, 'education');
    }
  }

  return fields;
};

/**
 * Run the parse pipeline for one task.
 *
 * Returns an outcome rather than throwing on a missing capability: "no provider
 * configured" is a deployment fact, not a failure to retry.
 */
export const runResumeParse = async (
  input: ParseInput,
  deps: { capabilities: AICapabilities; documents: DocumentStore },
): Promise<HandlerOutcome> => {
  const { documentParser, resumeExtractor } = deps.capabilities;
  if (documentParser === undefined || resumeExtractor === undefined) {
    // TEMPORARY: the document is fine, the environment is not. Marking this
    // permanent would discard a CV because a model was offline at upload time.
    return {
      kind: 'ABSTAIN', permanent: false,
      reason: 'No résumé parsing provider is configured.',
    };
  }

  const bytes = await deps.documents.get(input.fileHash);
  if (bytes === null) {
    // TEMPORARY: object stores are eventually consistent and mounts drop. The
    // blob is far more likely to be late than gone.
    return {
      kind: 'ABSTAIN', permanent: false,
      reason: `Document ${input.documentId} is not in storage.`,
    };
  }

  const parsed: AIOutcome<ParsedDocument> = await documentParser.parse({
    documentId: input.documentId,
    filename: input.fileName,
    mimeType: input.mimeType,
    bytes,
  });
  if (!isProposal(parsed)) {
    // The capability decides permanence; it is the only thing that knows
    // whether the input or the environment was at fault.
    return {
      kind: 'ABSTAIN', permanent: parsed.permanent,
      reason: `Could not read the document: ${parsed.reason}`,
    };
  }

  const extracted = await resumeExtractor.extract(parsed.content);
  if (!isProposal(extracted)) {
    return {
      kind: 'ABSTAIN', permanent: extracted.permanent,
      reason: `Nothing could be extracted: ${extracted.reason}`,
    };
  }

  const fields = toProposedFields(extracted.content, extracted.confidence);
  if (fields.length === 0) {
    // PERMANENT: the extractor read the document and found nothing. A proposal
    // with no fields is a review screen with nothing on it.
    return {
      kind: 'ABSTAIN', permanent: true,
      reason: 'No candidate fields could be extracted.',
    };
  }

  return {
    kind: 'PROPOSAL',
    fields,
    generation: {
      capability: extracted.provenance.capability,
      modelId: extracted.provenance.modelId,
      modelDigest: extracted.provenance.modelDigest ?? null,
      promptVersionId: extracted.provenance.promptVersionId,
      documentHash: input.fileHash,
      parserVersion: documentParser.version ?? null,
      extractorVersion: resumeExtractor.version ?? null,
      generatedAt: extracted.provenance.producedAt,
    },
  };
};
