// Résumé parsing — capability wiring, no model.
//
// The whole feature, expressed as: read the document, parse it, extract fields,
// raise a PROPOSAL. Nothing here writes to a candidate; `ProposalService` and
// the aggregate own that, and a human still has to accept every field.
//
// WORKS WITH NO AI CONFIGURED. If either capability is absent the task ABSTAINS
// with a reason. Abstention is a normal outcome, not an error — the candidate
// record is unaffected and the recruiter carries on typing.

import type {
  AICapabilities, AIOutcome, ExtractedResume, FieldEvidence, ParsedDocument,
  StructuredDocument,
} from '../../modules/shared/kernel/ai/index.js';
import { isProposal } from '../../modules/shared/kernel/ai/index.js';
import type { DocumentStore, EvidenceRef } from '../../modules/talent/index.js';
import { isProposableField } from '../../modules/talent/index.js';
import { structureOf } from './document/structure-builder.js';
import { locateDigits, locateValue } from './extraction/evidence-locator.js';
import { crossValidate, validateField } from './extraction/validate.js';

/**
 * One parse, two possible destinations.
 *
 * A CV attached to an existing candidate produces a PROPOSAL; a file staged in
 * an intake batch has no candidate to propose against, so the result is
 * recorded on the intake item instead. The parsing itself is identical, which
 * is why this is a union of targets rather than a second pipeline.
 */
export interface ParseInput {
  readonly candidateId?: number;
  readonly batchId?: number;
  readonly itemId?: string;
  readonly documentId: string;
  readonly fileHash: string;
  readonly fileName: string;
  readonly mimeType: string;
}

export interface ProposedFieldInput {
  readonly field: string;
  readonly value: unknown;
  /**
   * 0..1, PRESENTATION ONLY.
   *
   * It is not a gate anywhere in this file and must not become one. What
   * decides whether a value may be proposed is: it was located in the document,
   * and deterministic validation accepted it. A number cannot substitute for
   * either, which is exactly the mistake the parser this replaces made.
   */
  readonly confidence: number;
  readonly evidence: string | null;
  /** Machine-readable source location, when one could be cited. */
  readonly evidenceRef?: EvidenceRef;
}

/**
 * A value the extractor produced that was NOT proposed, and why.
 *
 * Recorded rather than discarded: "the model claimed a location that is nowhere
 * in the CV" is an operational signal about the model, and silently dropping it
 * makes that invisible.
 */
export interface WithheldField {
  readonly field: string;
  readonly value: unknown;
  readonly reason: string;
}

/**
 * Everything needed to reproduce this proposal exactly.
 *
 * Model alone is not enough: the same model behind a different parser or a
 * different prompt version produces different output. When a model is upgraded
 * this is what tells you which proposals were generated by the old one.
 */
export interface GenerationProvenance {
  readonly capability: string;
  readonly modelId: string;
  /** Digest of the exact weights, when the runtime reports one. See AIProvenance. */
  readonly modelDigest?: string | null;
  readonly promptVersionId: string;
  readonly documentHash: string | null;
  readonly parserVersion: string | null;
  readonly extractorVersion: string | null;
  readonly generatedAt: Date;
}

export type HandlerOutcome =
  | {
      readonly kind: 'PROPOSAL';
      readonly fields: readonly ProposedFieldInput[];
      /** Extracted but not proposed. Never persisted; surfaced for operators. */
      readonly withheld: readonly WithheldField[];
      readonly generation: GenerationProvenance;
    }
  | { readonly kind: 'ABSTAIN'; readonly reason: string; readonly permanent: boolean };

/**
 * Map an extraction onto candidate fields.
 *
 * MAPPING ONLY — no inference and no defaulting. A field the extractor did not
 * produce is simply absent from the proposal rather than proposed as null,
 * because "I did not find a phone number" and "this person has no phone number"
 * are different claims and only one of them is safe to write.
 *
 * `uncertainFields` halves the per-field confidence so the review screen can
 * highlight exactly what the extractor was unsure about. One confidence number
 * for a whole résumé hides that the name was certain and the phone was a guess.
 */
export const toProposedFields = (
  resume: ExtractedResume,
  baseConfidence: number,
): readonly ProposedFieldInput[] => {
  const uncertain = new Set(resume.uncertainFields);
  const fields: ProposedFieldInput[] = [];

  const add = (field: string, value: unknown, evidence: string | null = null): void => {
    if (value === undefined || value === null) return;
    if (typeof value === 'string' && value.trim() === '') return;
    if (Array.isArray(value) && value.length === 0) return;
    fields.push({
      field,
      value,
      confidence: uncertain.has(field) ? baseConfidence / 2 : baseConfidence,
      evidence,
    });
  };

  add('fullName', resume.fullName);
  add('email', resume.email);
  add('phone', resume.phone);
  add('location', resume.location);
  add('linkedinUrl', resume.linkedinUrl);
  add('yearsExperience', resume.totalYearsExperience);
  add('skills', resume.skills);
  add('languages', resume.languages);
  add('certifications', resume.certifications);

  // Current role: the employment entry marked current, else the most recent.
  const current = resume.employment.find((e) => e.current === true) ?? resume.employment[0];
  if (current !== undefined) {
    add('currentCompany', current.employer, `employment: ${current.employer}`);
    add('currentPosition', current.title, `employment: ${current.employer}`);
  }

  const education = resume.education[0];
  if (education !== undefined) {
    add('university', education.institution, 'education');
    add('major', education.field, 'education');
    const year = Number(education.to);
    if (Number.isInteger(year) && year >= 1900 && year <= 2200) {
      add('graduationYear', year, 'education');
    }
  }

  return fields;
};

/* ------------------- evidence, validation, and withholding ----------------- */
//
// THE STAGE THAT MAKES AI ADVISORY IN PRACTICE. `toProposedFields` above is
// mapping and nothing else: it will happily carry a value the model invented.
// This stage asks two questions that the extractor cannot answer about itself:
//
//   1. IS IT IN THE DOCUMENT?  Answered by searching the parsed structure. The
//      extractor's own claim to have read it is not evidence.
//   2. IS IT WELL-FORMED?      Answered by deterministic rules that never see
//      the model, its prompt, or its confidence.
//
// Only a value that passes BOTH is proposed — and even then it is proposed as
// PENDING, because approval is a human act. Everything else is withheld with a
// reason. Confidence is computed for display afterwards and gates nothing.

const refOf = (evidence: FieldEvidence): EvidenceRef => ({
  page: evidence.location.page,
  blockId: evidence.location.blockId,
  ...(evidence.location.sectionId !== undefined
    ? { section: evidence.location.sectionId } : {}),
  ...(evidence.location.charStart !== undefined
    ? { startOffset: evidence.location.charStart } : {}),
  ...(evidence.location.charEnd !== undefined
    ? { endOffset: evidence.location.charEnd } : {}),
});

/** Locate a value in the document. Digits for phones, text for everything else. */
const findEvidence = (
  structure: StructuredDocument,
  field: string,
  value: unknown,
): readonly FieldEvidence[] => {
  if (field === 'phone') return locateDigits(structure, String(value).replace(/\D/g, ''));
  if (field === 'yearsExperience') {
    // A bare small integer matches almost anything — "14" is inside "2014", so
    // locating the number alone produced a real value cited to an unrelated
    // employment line. Only a phrase like "14 years" counts as the CV stating
    // it; otherwise this falls through to the derived path, which says plainly
    // that the figure was computed from the dates.
    const n = String(value);
    return [...locateValue(structure, `${n} year`, { limit: 1 })];
  }
  if (Array.isArray(value)) {
    // A list is supported when its members are; locating the joined string
    // would fail on every CV that writes skills as bullets.
    const hits: FieldEvidence[] = [];
    for (const item of value) {
      const found = locateValue(structure, String(item), { limit: 1 });
      if (found.length > 0 && hits.length < 3) hits.push(...found);
    }
    return hits;
  }
  return locateValue(structure, String(value), { limit: 2 });
};

/** Presentation weights. Agreement between two independent readers is earned. */
const CONFIDENCE = { ai: 0.75, derived: 0.5 } as const;

/**
 * The block a derived value was computed from.
 *
 * Total years of experience is arithmetic over the employment dates, so the
 * citation for it is the place those dates are printed. Tries each employment
 * period in turn — earliest first, since that is the one that sets the span —
 * and falls back to the employer name, which is always on the same line as its
 * dates on a CV.
 */
const derivationAnchor = (
  structure: StructuredDocument,
  resume: ExtractedResume,
): FieldEvidence | null => {
  const jobs = [...resume.employment].reverse(); // earliest first
  for (const job of jobs) {
    for (const needle of [job.from, job.to, job.employer]) {
      if (needle === undefined || String(needle).trim() === '') continue;
      const hit = locateValue(structure, String(needle), { limit: 1 });
      if (hit.length > 0 && hit[0] !== undefined) return hit[0];
    }
  }
  return null;
};

/**
 * Fields a reader may legitimately DERIVE rather than copy.
 *
 * Total years of experience is normally not written anywhere on a CV — it is
 * the span of the employment history, which a reader computes. Requiring it to
 * be quoted verbatim, as the evidence gate does for every other field, meant it
 * was withheld from essentially every CV that did not happen to print the
 * sentence "12 years of experience".
 *
 * Deliberately a single field. The gate exists because an invented employer or
 * qualification is a real harm; an arithmetic result over dates that ARE in the
 * document is a different thing, and it carries a lower confidence to say so.
 */
const DERIVABLE: ReadonlySet<string> = new Set(['yearsExperience']);

export interface BuildFieldsInput {
  readonly resume: ExtractedResume;
  readonly document: ParsedDocument;
  /** The extractor's own confidence. Used for display only, and capped. */
  readonly aiConfidence: number;
  readonly parser?: string;
  readonly parserVersion?: string;
}

/**
 * Turn an extraction into the fields a `CandidateProposal` may be raised from.
 *
 * Returns proposable fields and withheld ones. Nothing here decides anything is
 * approved: every returned field becomes a PENDING entry a person still has to
 * accept.
 */
export const buildProposedFields = (input: BuildFieldsInput): {
  readonly fields: readonly ProposedFieldInput[];
  readonly withheld: readonly WithheldField[];
} => {
  const structure = structureOf(
    input.document, input.parser ?? 'unknown-parser', input.parserVersion ?? 'unversioned',
  );

  const fields: ProposedFieldInput[] = [];
  const withheld: WithheldField[] = [];

  /* 1. the model's claims, as plain mapped values — the only reader now */
  const claimed = new Map(
    toProposedFields(input.resume, input.aiConfidence).map((f) => [f.field, f]),
  );

  /* 2. judge each claimed field */
  const accepted = new Map<string, unknown>();

  for (const [field, claim] of claimed) {
    // The aggregate would drop a non-proposable field anyway; not raising it
    // keeps the review screen honest about what a reviewer can act on.
    if (!isProposableField(field)) continue;

    const value = claim.value;
    if (value === undefined || value === null) continue;

    const source: keyof typeof CONFIDENCE = 'ai';

    /* 2a. IS IT IN THE DOCUMENT? */
    const evidence = findEvidence(structure, field, value);
    if (evidence.length === 0 && DERIVABLE.has(field)) {
      // Derived, not quoted. The total never appears as text, but the dates it
      // was computed FROM do — so cite those. A reviewer checking a derived
      // number needs to land on the employment history, not on a bare
      // assertion, and every proposed field carries a source block for exactly
      // that reason.
      const anchor = derivationAnchor(structure, input.resume);
      if (anchor === null) {
        // Nothing in the document supports the arithmetic either. That is the
        // hallucination gate's case, not a derivation.
        withheld.push({
          field, value, reason: 'the value could not be located in the document',
        });
        continue;
      }
      fields.push({
        field,
        value,
        confidence: CONFIDENCE.derived,
        evidence: `Derived from the employment dates in this CV, not stated verbatim. ${anchor.snippet}`.trim(),
        evidenceRef: refOf(anchor),
      });
      continue;
    }
    if (evidence.length === 0) {
      // THE HALLUCINATION GATE. A value the document does not contain is not
      // proposed at all — not proposed with low confidence, not flagged for
      // review. There is nothing for a reviewer to check it against.
      withheld.push({
        field, value, reason: 'the value could not be located in the document',
      });
      continue;
    }

    /* 3b. IS IT WELL-FORMED? */
    const validation = validateField(field, value);
    if (validation.state === 'invalid') {
      withheld.push({
        field, value, reason: validation.note ?? 'the value failed deterministic validation',
      });
      continue;
    }

    accepted.set(field, value);
    const first = evidence[0];
    fields.push({
      field,
      value,
      confidence: source === 'ai'
        ? Math.min(input.aiConfidence, CONFIDENCE.ai)
        : CONFIDENCE[source],
      evidence: first?.snippet ?? null,
      ...(first !== undefined ? { evidenceRef: refOf(first) } : {}),
    });
  }

  /* 4. rules that need more than one field */
  const conflicts = crossValidate(accepted);
  if (conflicts.length === 0) return { fields, withheld };

  const conflicted = new Map(conflicts.map((c) => [c.field, c.note]));
  return {
    fields: fields.filter((f) => !conflicted.has(f.field)),
    withheld: [
      ...withheld,
      ...fields.filter((f) => conflicted.has(f.field)).map((f) => ({
        field: f.field,
        value: f.value,
        reason: conflicted.get(f.field) ?? 'conflicts with another field',
      })),
    ],
  };
};

/**
 * Run the parse pipeline for one task.
 *
 * Returns an outcome rather than throwing on a missing capability: "no provider
 * configured" is a deployment fact, not a failure to retry.
 */
export const runResumeParse = async (
  input: ParseInput,
  deps: { capabilities: AICapabilities; documents: DocumentStore },
): Promise<HandlerOutcome> => {
  const { documentParser, resumeExtractor } = deps.capabilities;
  if (documentParser === undefined || resumeExtractor === undefined) {
    // TEMPORARY: the document is fine, the environment is not. Marking this
    // permanent would discard a CV because a model was offline at upload time.
    return {
      kind: 'ABSTAIN', permanent: false,
      reason: 'No résumé parsing provider is configured.',
    };
  }

  const bytes = await deps.documents.get(input.fileHash);
  if (bytes === null) {
    // TEMPORARY: object stores are eventually consistent and mounts drop. The
    // blob is far more likely to be late than gone.
    return {
      kind: 'ABSTAIN', permanent: false,
      reason: `Document ${input.documentId} is not in storage.`,
    };
  }

  const parsed: AIOutcome<ParsedDocument> = await documentParser.parse({
    documentId: input.documentId,
    filename: input.fileName,
    mimeType: input.mimeType,
    bytes,
  });
  if (!isProposal(parsed)) {
    // The capability decides permanence; it is the only thing that knows
    // whether the input or the environment was at fault.
    return {
      kind: 'ABSTAIN', permanent: parsed.permanent,
      reason: `Could not read the document: ${parsed.reason}`,
    };
  }

  const extracted = await resumeExtractor.extract(parsed.content);
  if (!isProposal(extracted)) {
    return {
      kind: 'ABSTAIN', permanent: extracted.permanent,
      reason: `Nothing could be extracted: ${extracted.reason}`,
    };
  }

  const { fields, withheld } = buildProposedFields({
    resume: extracted.content,
    document: parsed.content,
    aiConfidence: extracted.confidence,
    parser: documentParser.version ?? 'unversioned',
    parserVersion: documentParser.version ?? 'unversioned',
  });

  if (fields.length === 0) {
    // PERMANENT: nothing survived evidence location and validation. A proposal
    // with no fields is a review screen with nothing on it — and filling it
    // from the withheld values is exactly the invention this refuses.
    return {
      kind: 'ABSTAIN',
      permanent: true,
      reason: withheld.length === 0
        ? 'No candidate fields could be extracted.'
        : `No extracted field could be supported by the document (${withheld.length} withheld).`,
    };
  }

  return {
    kind: 'PROPOSAL',
    fields,
    withheld,
    generation: {
      capability: extracted.provenance.capability,
      modelId: extracted.provenance.modelId,
      modelDigest: extracted.provenance.modelDigest ?? null,
      promptVersionId: extracted.provenance.promptVersionId,
      documentHash: input.fileHash,
      parserVersion: documentParser.version ?? null,
      extractorVersion: resumeExtractor.version ?? null,
      generatedAt: extracted.provenance.producedAt,
    },
  };
};
